auto transcribe new messages, add requirements.txt
dromzeh/vmt pull request #2
Opened 2023-07-11 15:52 UTC by strazto

2023-07-11 22:11 UTC, dromzeh requested changes

2023-07-11 22:11 UTC, dromzeh commented on src/cogs/transcribe.py
> +        if not msg_has_voice_note(msg): return None
change to `if not msg or msg_has_voice_note(msg): return None`?

2023-07-12 00:27 UTC, strazto commented on src/cogs/transcribe.py
> +        if not msg_has_voice_note(msg): return None
Can do, if you like, but `msg_has_voice_note(msg)` already returns falsy if `msg` is `None`

2023-07-12 00:32 UTC, strazto commented
Btw, most significant change besides UX change from just autotranscribing, I changed the attributions in the embed -
I remove the Google / deepl attributions, and link back to this repo, as well as our profiles.

Anyone who cares about the Google / deepl stuff can find out via the readme, which also boosts your profile hahaha.

2023-07-12 00:34 UTC, dromzeh commented on src/cogs/transcribe.py
> +        if not msg_has_voice_note(msg): return None
> Can do, if you like, but `msg_has_voice_note(msg)` already returns falsy if `msg` is `None`

yeah, just suggested this as we should probably check for message before accessing the attributes?(https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportOptionalMemberAccess)

2023-07-12 01:45 UTC, strazto commented on src/cogs/transcribe.py
> +        if not msg_has_voice_note(msg): return None
https://github.com/dromzeh/vmt/pull/2/files#diff-f2aa232874979931df2f97adb45268db77ba080ed496efd59e6f18d8776deaeeR151  this line checks message before accessing attributes too :)

2023-07-12 01:52 UTC, strazto commented on src/cogs/transcribe.py
> +        if not msg_has_voice_note(msg): return None
I don't have pyright set up in my env, is it giving an warning?

2023-07-12 01:55 UTC, dromzeh commented on src/cogs/transcribe.py
> +        if not msg_has_voice_note(msg): return None
> I don't have pyright set up in my env, is it giving an warning?

yes - `if not msg...` removes that

2023-07-12 02:00 UTC, strazto commented on src/cogs/transcribe.py
> +        if not msg_has_voice_note(msg): return None
done :)

2023-07-12 02:00 UTC, dromzeh approved these changes

2023-07-12 02:03 UTC, dromzeh approved these changes
lgtm :)

2023-07-12 02:03 UTC, merged